"""Added_yandex_acc_token_column

Revision ID: 72ebbf259f6c
Revises: a4de5acd309a
Create Date: 2025-05-27 21:57:46.830581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ebbf259f6c'
down_revision: Union[str, None] = 'a4de5acd309a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('UserProfile', sa.Column('yandex_access_token', sa.String(), nullable=True))
    op.drop_column('UserProfile', 'google_or_yandex_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('google_or_yandex_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('UserProfile', 'yandex_access_token')
    op.drop_column('UserProfile', 'google_access_token')
    # ### end Alembic commands ###
