"""Changed_name_of_access_token_column

Revision ID: 9a8de7d7f6fa
Revises: 8376b36264c2
Create Date: 2025-05-27 21:25:24.085554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8de7d7f6fa'
down_revision: Union[str, None] = '8376b36264c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('google_or_yandex_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('UserProfile', 'google_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('google_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('UserProfile', 'google_or_yandex_access_token')
    # ### end Alembic commands ###
